---
- project:
    merge-mode: squash-merge
    vars:
      sphinx_source_dir: source
      sphinx_build_dir: build
    check:
      jobs:
        - build-sphinx-docs
        - python-black
    gate:
      jobs:
        - build-sphinx-docs
        - python-black
