extensions = ['sphinxcontrib.blockdiag', 'sphinxcontrib.nwdiag', 'sphinx.ext.todo']
source_suffix = '.rst'
master_doc = 'index'
project = u'OpenStack Infrastructure & Service Manager'
copyright = u'2017, Betacloud Solutions GmbH'
author = u'Betacloud Solutions GmbH'
version = u'1.0.0'
release = u'1.0.0'
language = 'en'
exclude_patterns = []
pygments_style = 'sphinx'
todo_include_todos = True
html_theme = 'flask'
html_show_sphinx = False
html_show_sourcelink = False
html_show_copyright = True
htmlhelp_basename = 'documentation'
html_theme_options = {}
latex_elements = {}
