extensions = ['sphinxcontrib.blockdiag', 'sphinxcontrib.nwdiag', 'sphinx.ext.todo', 'sphinx_fontawesome']
source_suffix = '.rst'
master_doc = 'index'
project = u'Open Source Infrastructure & Service Manager'
copyright = u'2017-2019, Betacloud Solutions GmbH'
author = u'Betacloud Solutions GmbH'
version = u''
release = u''
language = 'en'
exclude_patterns = []
pygments_style = 'sphinx'
todo_include_todos = True
html_theme = 'alabaster'
html_show_sphinx = False
html_show_sourcelink = False
html_show_copyright = True
htmlhelp_basename = 'documentation'
html_theme_options = {}
latex_elements = {}
