extensions = ['sphinxcontrib.blockdiag', 'sphinxcontrib.nwdiag', 'sphinx.ext.todo']
source_suffix = '.rst'
master_doc = 'index'
project = u'OSISM'
copyright = u'2017-2018, Betacloud Solutions GmbH'
author = u'Betacloud Solutions GmbH'
version = u'master'
release = u'master'
language = 'en'
exclude_patterns = []
pygments_style = 'sphinx'
todo_include_todos = True
html_theme = 'sphinx_rtd_theme'
html_show_sphinx = False
html_show_sourcelink = False
html_show_copyright = True
htmlhelp_basename = 'documentation'
html_theme_options = {}
latex_elements = {}
