---
name: Build documentation

"on":
  workflow_dispatch:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/build-documentation.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'source/**'
      - '.github/workflows/build-documentation.yml'

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install -r test-requirements.txt
      - run: sphinx-build -b html source build/html
      - uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          local-dir: build/html/
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: strict
          server-dir: /osism/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          exclude: '
            - testbed/**
            - reference/**
            '
        if: |
          github.repository == 'osism/documentation' &&
          github.ref == 'refs/heads/main'
