---
name: Sphinx

on:
  push:
    paths:
      - 'source/**'
  pull_request:
    paths:
      - 'source/**'

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: sphinx-build -b html source build/html
